export default {
  login: "lucifer2355",
  id: 49318010,
  node_id: "MDQ6VXNlcjQ5MzE4MDEw",
  avatar_url: "https://avatars2.githubusercontent.com/u/49318010?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/lucifer2355",
  html_url: "https://github.com/lucifer2355",
  followers_url: "https://api.github.com/users/lucifer2355/followers",
  following_url:
    "https://api.github.com/users/lucifer2355/following{/other_user}",
  gists_url: "https://api.github.com/users/lucifer2355/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/lucifer2355/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/lucifer2355/subscriptions",
  organizations_url: "https://api.github.com/users/lucifer2355/orgs",
  repos_url: "https://api.github.com/users/lucifer2355/repos",
  events_url: "https://api.github.com/users/lucifer2355/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/lucifer2355/received_events",
  type: "User",
  site_admin: false,
  name: "Dhruvil Gajjar",
  company: "Codrain Technolab PVT LTD",
  blog: "dhruvilgajjar.engineer",
  location: "Ahemdabad, Gujarat , India",
  email: null,
  hireable: null,
  bio: "<HelloWorld hobby='Thinking' favLang='JavaScript' />",
  twitter_username: "lucifer2355",
  public_repos: 27,
  public_gists: 0,
  followers: 3,
  following: 3,
  created_at: "2019-04-05T16:32:12Z",
  updated_at: "2020-10-20T18:43:25Z",
};
